residual_images:
  num_frames: -1
  # plot images
  debug: False
  # normalize/scale the difference with corresponding range value
  normalize: True
  # use the last n frame to calculate the difference image
  num_last_n: [1,2]
  seqs: ["00","01","02","03","04","05","06","07","08","09","10", "11", "12", "13"]

  # Outputs
  # the suffix should be the same as num_last_n!
  residual_image_folder: '/home/joe46973/Masterarbeit/data/KITTI/dataset/sequences/SEQ_NUM/residual_images_1'
  visualize: True
  visualization_folder: '/home/joe46973/Masterarbeit/data/KITTI/dataset/sequences/SEQ_NUM/visualization_1'

dataset:
  root_folder: '/home/joe46973/Masterarbeit/data/KITTI/dataset/sequences/' # where sequences are stored
  scan_folder: 'velodyne'
  pose_file: 'poses.txt'
  calib_file: 'calib.txt'
  sensor:
    height: 64
    width: 2048
    fov_up: 3.0
    fov_down: -25.0
    max_range: 50.0
    min_range: 2.0
