################################################################################
# generate residual images
################################################################################
residual_images:
  num_frames: -1
  # plot images
  debug: False
  # normalize/scale the difference with corresponding range value
  normalize: False
  # use the last n frame to calculate the difference image
  num_last_n: [1,2,3]
  seqs: ["Sequence_12"]

  # Outputs
  residual_image_folder: '/home/joe46973/Masterarbeit/data/MODISSA/sequences/SEQ_NUM/SENSOR/residual_images_'
  visualize: True
  visualization_folder: '/home/joe46973/Masterarbeit/data/MODISSA/sequences/SEQ_NUM/SENSOR/visualization_'


################################################################################
# training parameters
################################################################################
train:
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 150
  lr: 0.01               # sgd learning rate
  wup_epochs: 1          # warmup during first XX epochs (can be float)
  momentum: 0.9          # sgd momentum
  lr_decay: 0.99         # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.0001        # weight decay
  batch_size: 8         # batch size
  report_batch: 10       # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  save_summary: True    # Summary of weight histograms for tensorboard
  save_scans: True       # False doesn't save anything, True saves some
    # sample images (one per batch of the last calculated batch)
  # in log folder
  show_scans: False      # show scans during training
  workers: 4             # number of threads to get data
################################################################################
# infer parameters
################################################################################
infer:
  ground_truth: false
  
################################################################################
# postproc parameters
################################################################################
post:
  CRF:
    use: False
    train: True
    params: False # this should be a dict when in use
  KNN:
    use: True # This parameter default is false
    params:
      knn: 5
      search: 5
      sigma: 1.0
      cutoff: 1.0

################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  root_folder: '/home/joe46973/Masterarbeit/data/MODISSA/sequences/' # where sequences are stored
  scan_folder: 'KITTI_BIN'
  pose_file: 'poses.txt'
  calib_file: 'calib.txt'
  filter_points: True
  sensor:
    name: "o2"
    type: "spherical" # projective
    height: 128
    width: 2048
    fov_up: 11.25
    fov_down: -11.25
    max_range: 50.0
    min_range: 2.0
    img_means: #range,x,y,z,signal
      - 12.12
      - 10.88
      - 0.23
      - -1.04
      - 0.21
    img_stds: #range,x,y,z,signal
      - 12.32
      - 11.47
      - 6.91
      - 0.86
      - 0.16
    transform: False # tranform the last n_input_scans - 1 frames before concatenation
    residual: True
  labels: "modissa"
  max_points: 264000 # max of any scan in dataset


################################################################################
# labels
################################################################################
labels:
  name: "modissa"
  labels: 
    0 : "unlabeled"
    1 : "outlier"
    9 : "static"     # for mos static
    10: "car"
    11: "bicycle"
    13: "bus"
    15: "motorcycle"
    16: "on-rails"
    18: "truck"
    20: "other-vehicle"
    30: "person"
    31: "bicyclist"
    32: "motorcyclist"
    40: "road"
    44: "parking"
    48: "sidewalk"
    49: "other-ground"
    50: "building"
    51: "fence"
    52: "other-structure"
    60: "lane-marking"
    70: "vegetation"
    71: "trunk"
    72: "terrain"
    80: "pole"
    81: "traffic-sign"
    99: "other-object"
    251: "moving"      # for mos moving
    252: "moving-car"
    253: "moving-bicyclist"
    254: "moving-person"
    255: "moving-motorcyclist"
    256: "moving-on-rails"
    257: "moving-bus"
    258: "moving-truck"
    259: "moving-other-vehicle"
  color_map: # bgr
    0 : [0, 0, 0]
    1 : [0, 0, 255]  
    9 : [0, 0, 0]     # for mos static
    10: [245, 150, 100]
    11: [245, 230, 100]
    13: [250, 80, 100]
    15: [150, 60, 30]
    16: [255, 0, 0]
    18: [180, 30, 80]
    20: [255, 0, 0]
    30: [30, 30, 255]
    31: [200, 40, 255]
    32: [90, 30, 150]
    40: [255, 0, 255]
    44: [255, 150, 255]
    48: [75, 0, 75]
    49: [75, 0, 175]
    50: [0, 200, 255]
    51: [50, 120, 255]
    52: [0, 150, 255]
    60: [170, 255, 150]
    70: [0, 175, 0]
    71: [0, 60, 135]
    72: [80, 240, 150]
    80: [150, 240, 255]
    81: [0, 0, 255]
    99: [255, 255, 50]
    251: [255, 255, 255]  # for mos moving
    252: [245, 150, 100]
    256: [255, 0, 0]
    253: [255, 0, 0]
    254: [30, 30, 255]
    255: [90, 30, 150]
    257: [250, 80, 100]
    258: [180, 30, 80]
    259: [255, 0, 0]
  content: # as a ratio with the total number of points
    0: 0.018889854628292943
    1: 0.0002937197336781505
    10: 0.040818519255974316
    11: 0.00016609538710764618
    13: 2.7879693665067774e-05
    15: 0.00039838616015114444
    16: 0.0
    18: 0.0020633612104619787
    20: 0.0016218197275284021
    30: 0.00017698551338515307
    31: 1.1065903904919655e-08
    32: 5.532951952459828e-09
    40: 0.1987493871255525
    44: 0.014717169549888214
    48: 0.14392298360372
    49: 0.0039048553037472045
    50: 0.1326861944777486
    51: 0.0723592229456223
    52: 0.002395131480328884
    60: 4.7084144280367186e-05
    70: 0.26681502148037506
    71: 0.006035012012626033
    72: 0.07814222006271769
    80: 0.002855498193863172
    81: 0.0006155958086189918
    99: 0.009923127583046915
    252: 0.001789309418528068
    253: 0.00012709999297008662
    254: 0.00016059776092534436
    255: 3.745553104802113e-05
    256: 0.0
    257: 0.00011351574470342043
    258: 0.00010157861367183268
    259: 4.3840131989471124e-05
  # classes that are indistinguishable from single scan or inconsistent in
  # ground truth are mapped to their closest equivalent
  learning_map:
    0 : 0     # "unlabeled"       mapped to "unlabeled" ------------------------mapped
    1 : 0     # "outlier"         mapped to "unlabeled" ------------------------mapped
    9 : 1     # "car"             mapped to "static" ---------------------------mapped
    10: 1     # "car"             mapped to "static" ---------------------------mapped
    11: 1     # "bicycle"         mapped to "static" ---------------------------mapped
    13: 1     # "bus"             mapped to "static" ---------------------------mapped
    15: 1     # "motorcycle"      mapped to "static" ---------------------------mapped
    16: 1     # "on-rails"        mapped to "static" ---------------------------mapped
    18: 1     # "truck"           mapped to "static" ---------------------------mapped
    20: 1     # "other-vehicle"   mapped to "static" ---------------------------mapped
    30: 1     # "person"          mapped to "static" ---------------------------mapped
    31: 1     # "bicyclist"       mapped to "static" ---------------------------mapped
    32: 1     # "motorcyclist"    mapped to "static" ---------------------------mapped
    40: 1     # "road"            mapped to "static" ---------------------------mapped
    44: 1    # "parking"          mapped to "static" ---------------------------mapped
    48: 1    # "sidewalk"         mapped to "static" ---------------------------mapped
    49: 1    # "other-ground"     mapped to "static" ---------------------------mapped
    50: 1    # "building"         mapped to "static" ---------------------------mapped
    51: 1    # "fence"            mapped to "static" ---------------------------mapped
    52: 1     # "other-structure" mapped to "static" ---------------------------mapped
    60: 1     # "lane-marking"    mapped to "static" ---------------------------mapped
    70: 1    # "vegetation"       mapped to "static" ---------------------------mapped
    71: 1    # "trunk"            mapped to "static" ---------------------------mapped
    72: 1    # "terrain"          mapped to "static" ---------------------------mapped
    80: 1    # "pole"             mapped to "static" ---------------------------mapped
    81: 1    # "traffic-sign"     mapped to "static" ---------------------------mapped
    99: 1     # "other-object"    mapped to "static" ---------------------------mapped
    251: 2    # "moving-car"          mapped to "moving" ---------------------------mapped
    252: 2    # "moving-car"          mapped to "moving" ---------------------------mapped
    253: 2    # "moving-bicyclist"    mapped to "moving" ---------------------------mapped
    254: 2    # "moving-person"       mapped to "moving" ---------------------------mapped
    255: 2    # "moving-motorcyclist" mapped to "moving" ---------------------------mapped
    256: 2    # "moving-on-rails"     mapped to "moving" ---------------------------mapped
    257: 2    # "moving-bus"          mapped to "moving" ---------------------------mapped
    258: 2    # "moving-truck"        mapped to "moving" ---------------------------mapped
    259: 2    # "moving-other"        mapped to "moving" ---------------------------mapped
  learning_map_inv: # inverse of previous map
    0: 0      # "unlabeled", and others ignored
    1: 9      # "static"
    2: 251    # "moving"

  learning_ignore: # Ignore classes
    0: True      # "unlabeled", and others ignored
    1: False     # "car"
    2: False     # "bicycle"
    3: False     # "motorcycle"
    4: False     # "truck"
    5: False     # "other-vehicle"
    6: False     # "person"
    7: False     # "bicyclist"
    8: False     # "motorcyclist"
    9: False     # "road"
    10: False    # "parking"
    11: False    # "sidewalk"
    12: False    # "other-ground"
    13: False    # "building"
    14: False    # "fence"
    15: False    # "vegetation"
    16: False    # "trunk"
    17: False    # "terrain"
    18: False    # "pole"
    19: False    # "traffic-sign"

split: # sequence numbers
  train:
    - Sequence_0
    - Sequence_1
    - Sequence_2
  valid:
    - Sequence_12
  test:
    - 

